name: Publish Docker Azure image to ACR (GitHub Actions)

on:      
  workflow_dispatch:
    inputs:
      name:
        description: "Docker TAG"
        required: true
        default: "master"
    
jobs:
  push_to_registry:
    name: Push Docker image to ACR and update manifest
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 매니페스트 커밋/푸시 위해 필요
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      # ACR 로그인 (현재 방식 유지)
      - name: Log in to ACR (docker login)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      # 이미지 이름 메타 (명시적으로 ACR 경로 지정 권장)
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: ${{ github.event.inputs.name }}
      
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        id: buildpush
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.ACR }}/${{ env.IMAGE_PATH }}:${{ env.TAG }}
            ${{ env.ACR }}/${{ env.IMAGE_PATH }}:latest

      - name: Read pushed digest
        id: digest
        run: echo "digest=${{ steps.buildpush.outputs.digest }}" >> $GITHUB_OUTPUT

      - name: Update manifest to digest
        run: |
          FILE="k8s/deployment.yaml"
          REPO="${{ env.ACR }}/${{ env.IMAGE_PATH }}"
          DIGEST="${{ steps.digest.outputs.digest }}"
          sed -i "s#^\(\s*image:\s*\)${REPO}:.*#\1${REPO}@${DIGEST}#g" "$FILE"
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "$FILE"
          git commit -m "deploy: ${REPO}@${DIGEST}"
          git push
